### ISSUE TITLE
Do you know how to build ArmaditoAV

### ISSUE THREAD

**Issue by YT-Advanced** [Nithe14/ClamaAV-vs-ArmaditoAV#1]
Hello, I have read the document from Armadito but I can't understand it. Can you sent me the source file after built ???

**Comment by Nithe14** [comment]
Hi, I don't use Armadito anymore. I installed it on Ubuntu 16.04 virtual machine and there is an official package repository I used: https://launchpad.net/~armadito/+archive/ubuntu/armadito-av. As I know Armadito hasn't been updated since 2017 so there may be a problem using it on newer version of Ubuntu. Unfortunately I don't have a virtual machine image to share :/
